//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBSResourceAPI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Tour_Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tour_Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SBSResourceAPI.Tour_Resource", typeof(Tour_Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To add allowance/deduction, click here to add new record..
        /// </summary>
        public static string Info_addAllowanceRow {
            get {
                return ResourceManager.GetString("Info_addAllowanceRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowance amount will be displayed here..
        /// </summary>
        public static string Info_Allowance {
            get {
                return ResourceManager.GetString("Info_Allowance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if you want to add other deduction or allowance, go to this tab.
        /// </summary>
        public static string Info_allowance_tab {
            get {
                return ResourceManager.GetString("Info_allowance_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To add extra donation, click here..
        /// </summary>
        public static string Info_btnAddNewDonation {
            get {
                return ResourceManager.GetString("Info_btnAddNewDonation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To add OT record, click here..
        /// </summary>
        public static string Info_btnAddOT {
            get {
                return ResourceManager.GetString("Info_btnAddOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After select the period, just click here..
        /// </summary>
        public static string Info_btnRetrieveExpenses {
            get {
                return ResourceManager.GetString("Info_btnRetrieveExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After select the period, just click here..
        /// </summary>
        public static string Info_btnRetrieveLeave {
            get {
                return ResourceManager.GetString("Info_btnRetrieveLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to save the changes..
        /// </summary>
        public static string Info_btnSave {
            get {
                return ResourceManager.GetString("Info_btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to save and view the payslip..
        /// </summary>
        public static string Info_btnSaveView {
            get {
                return ResourceManager.GetString("Info_btnSaveView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deduction amount will be displayed here..
        /// </summary>
        public static string Info_Deductions {
            get {
                return ResourceManager.GetString("Info_Deductions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fund donation will be displayed here..
        /// </summary>
        public static string Info_Donation {
            get {
                return ResourceManager.GetString("Info_Donation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee CPF will be displayed here..
        /// </summary>
        public static string Info_Employee_Contribution {
            get {
                return ResourceManager.GetString("Info_Employee_Contribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer CPF will be displayed here..
        /// </summary>
        public static string Info_Employer_Contribution {
            get {
                return ResourceManager.GetString("Info_Employer_Contribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claimed Amount will be displayed here..
        /// </summary>
        public static string Info_Expenses_Amount {
            get {
                return ResourceManager.GetString("Info_Expenses_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The claim records will be appeared here if there is..
        /// </summary>
        public static string Info_expensesDataTable {
            get {
                return ResourceManager.GetString("Info_expensesDataTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra donation will be displayed here..
        /// </summary>
        public static string Info_Extra_Donation {
            get {
                return ResourceManager.GetString("Info_Extra_Donation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have extra donation,  go to this tab.
        /// </summary>
        public static string Info_extradonation_tab {
            get {
                return ResourceManager.GetString("Info_extradonation_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upaid Leave Amount will be displayed here..
        /// </summary>
        public static string Info_Leave_Amount {
            get {
                return ResourceManager.GetString("Info_Leave_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unpaid leave records will be appeared here if there is..
        /// </summary>
        public static string Info_leaveDataTable {
            get {
                return ResourceManager.GetString("Info_leaveDataTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the employee has any claims, you can pull the claim records here..
        /// </summary>
        public static string Info_li_expenses {
            get {
                return ResourceManager.GetString("Info_li_expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the employee has unpaid leave, you can pull the leave records here..
        /// </summary>
        public static string Info_li_leave {
            get {
                return ResourceManager.GetString("Info_li_leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overtime Charge will be displayed here..
        /// </summary>
        public static string Info_Overtime {
            get {
                return ResourceManager.GetString("Info_Overtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to enter the overtime amount, go to this tab..
        /// </summary>
        public static string Info_overtime_tab {
            get {
                return ResourceManager.GetString("Info_overtime_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &quot;From&quot;Date.
        /// </summary>
        public static string Info_Process_Date_From {
            get {
                return ResourceManager.GetString("Info_Process_Date_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &quot;To&quot;Date.
        /// </summary>
        public static string Info_Process_Date_To {
            get {
                return ResourceManager.GetString("Info_Process_Date_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &quot;From&quot;Date to pull out claim record.
        /// </summary>
        public static string Info_sExpenses_Period_From {
            get {
                return ResourceManager.GetString("Info_sExpenses_Period_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &quot;To&quot;Date to pull out claim record.
        /// </summary>
        public static string Info_sExpenses_Period_To {
            get {
                return ResourceManager.GetString("Info_sExpenses_Period_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &quot;From&quot;Date to pull out unpaid leave.
        /// </summary>
        public static string Info_sLeave_Period_From {
            get {
                return ResourceManager.GetString("Info_sLeave_Period_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &quot;To&quot;Date to pull out unpaid leave.
        /// </summary>
        public static string Info_sLeave_Period_To {
            get {
                return ResourceManager.GetString("Info_sLeave_Period_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter allowance amount.
        /// </summary>
        public static string Info_thAllowAmt {
            get {
                return ResourceManager.GetString("Info_thAllowAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Allowance name.
        /// </summary>
        public static string Info_thAllowName {
            get {
                return ResourceManager.GetString("Info_thAllowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Allowance type.
        /// </summary>
        public static string Info_thAllowType {
            get {
                return ResourceManager.GetString("Info_thAllowType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Info_thDAmt {
            get {
                return ResourceManager.GetString("Info_thDAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Info_thDType {
            get {
                return ResourceManager.GetString("Info_thDType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter OT amount.
        /// </summary>
        public static string Info_thOTAmt {
            get {
                return ResourceManager.GetString("Info_thOTAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter no. of OT hours.
        /// </summary>
        public static string Info_thOTHours {
            get {
                return ResourceManager.GetString("Info_thOTHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select OTPayment.
        /// </summary>
        public static string Info_thOTPayment {
            get {
                return ResourceManager.GetString("Info_thOTPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your CPF Submission number..
        /// </summary>
        public static string PAT_CPF_Config_Step1 {
            get {
                return ResourceManager.GetString("PAT_CPF_Config_Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your PAT User ID..
        /// </summary>
        public static string PAT_CPF_Config_Step2 {
            get {
                return ResourceManager.GetString("PAT_CPF_Config_Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your PAT password..
        /// </summary>
        public static string PAT_CPF_Config_Step3 {
            get {
                return ResourceManager.GetString("PAT_CPF_Config_Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set PAT-CPF Configuration.
        /// </summary>
        public static string PAT_CPF_Config_Tour_Title {
            get {
                return ResourceManager.GetString("PAT_CPF_Config_Tour_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the source of your company..
        /// </summary>
        public static string PAT_IR8A_Config_Step1 {
            get {
                return ResourceManager.GetString("PAT_IR8A_Config_Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the payer ID Type..
        /// </summary>
        public static string PAT_IR8A_Config_Step2 {
            get {
                return ResourceManager.GetString("PAT_IR8A_Config_Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the payer ID No..
        /// </summary>
        public static string PAT_IR8A_Config_Step3 {
            get {
                return ResourceManager.GetString("PAT_IR8A_Config_Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Branch..
        /// </summary>
        public static string PAT_IR8A_Config_Step4 {
            get {
                return ResourceManager.GetString("PAT_IR8A_Config_Step4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set PAT-IR8A Configuration.
        /// </summary>
        public static string PAT_IR8A_Config_Tour_Title {
            get {
                return ResourceManager.GetString("PAT_IR8A_Config_Tour_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll Info Detail.
        /// </summary>
        public static string Payroll_Info_Title {
            get {
                return ResourceManager.GetString("Payroll_Info_Title", resourceCulture);
            }
        }
    }
}
