// <auto-generated />
namespace HR.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class hr_intasp : IMigrationMetadata
    {
        private  ResourceManager Resources = new ResourceManager(typeof(hr_intasp));
        
        string IMigrationMetadata.Id
        {
            get { return "201401181936291_hr_intasp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
