//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcePayroll {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcePayroll() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourcePayroll", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Donation.
        /// </summary>
        internal static string AddDonation {
            get {
                return ResourceManager.GetString("AddDonation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Extra Donation.
        /// </summary>
        internal static string AddExtraDonation {
            get {
                return ResourceManager.GetString("AddExtraDonation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Information.
        /// </summary>
        internal static string AdditionalInformation {
            get {
                return ResourceManager.GetString("AdditionalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Payment.
        /// </summary>
        internal static string AdditionalPayment {
            get {
                return ResourceManager.GetString("AdditionalPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment (Addition).
        /// </summary>
        internal static string Adjustment_Addition {
            get {
                return ResourceManager.GetString("Adjustment_Addition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment (Deduction).
        /// </summary>
        internal static string Adjustment_Deduction {
            get {
                return ResourceManager.GetString("Adjustment_Deduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AGM.
        /// </summary>
        internal static string AGM {
            get {
                return ResourceManager.GetString("AGM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowance/Deduction.
        /// </summary>
        internal static string Allowance {
            get {
                return ResourceManager.GetString("Allowance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowance Amount.
        /// </summary>
        internal static string AllowanceAmount {
            get {
                return ResourceManager.GetString("AllowanceAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowance Type.
        /// </summary>
        internal static string AllowanceType {
            get {
                return ResourceManager.GetString("AllowanceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string AllowanceTypeName {
            get {
                return ResourceManager.GetString("AllowanceTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowance.
        /// </summary>
        internal static string Allowance_ {
            get {
                return ResourceManager.GetString("Allowance_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowance Type.
        /// </summary>
        internal static string Allowance_Type {
            get {
                return ResourceManager.GetString("Allowance_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount ($).
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Deductable ($).
        /// </summary>
        internal static string AmountDeductable {
            get {
                return ResourceManager.GetString("AmountDeductable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Payable ($).
        /// </summary>
        internal static string AmountPayable {
            get {
                return ResourceManager.GetString("AmountPayable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Amount_ {
            get {
                return ResourceManager.GetString("Amount_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Payable.
        /// </summary>
        internal static string Amount_Payable {
            get {
                return ResourceManager.GetString("Amount_Payable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicable for.
        /// </summary>
        internal static string ApplicableFor {
            get {
                return ResourceManager.GetString("ApplicableFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Employee.
        /// </summary>
        internal static string AssignEmployee {
            get {
                return ResourceManager.GetString("AssignEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign HR.
        /// </summary>
        internal static string AssignHR {
            get {
                return ResourceManager.GetString("AssignHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization.
        /// </summary>
        internal static string Authorization {
            get {
                return ResourceManager.GetString("Authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Salary.
        /// </summary>
        internal static string BasicSalary {
            get {
                return ResourceManager.GetString("BasicSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic salary details.
        /// </summary>
        internal static string BasicSalaryDetails {
            get {
                return ResourceManager.GetString("BasicSalaryDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus.
        /// </summary>
        internal static string Bonus {
            get {
                return ResourceManager.GetString("Bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus Amount.
        /// </summary>
        internal static string BonusAmount {
            get {
                return ResourceManager.GetString("BonusAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Bonus this month.
        /// </summary>
        internal static string BonusIssue {
            get {
                return ResourceManager.GetString("BonusIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakdown of Additional Payment.
        /// </summary>
        internal static string BreakdownOfAdditionalPayment {
            get {
                return ResourceManager.GetString("BreakdownOfAdditionalPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakdown of Allowance.
        /// </summary>
        internal static string BreakdownOfAllowance {
            get {
                return ResourceManager.GetString("BreakdownOfAllowance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakdown of Deductions.
        /// </summary>
        internal static string BreakdownOfDeductions {
            get {
                return ResourceManager.GetString("BreakdownOfDeductions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation.
        /// </summary>
        internal static string Calculation {
            get {
                return ResourceManager.GetString("Calculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        internal static string Cash {
            get {
                return ResourceManager.GetString("Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CDAC.
        /// </summary>
        internal static string CDAC {
            get {
                return ResourceManager.GetString("CDAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheque.
        /// </summary>
        internal static string Cheque {
            get {
                return ResourceManager.GetString("Cheque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheque No.
        /// </summary>
        internal static string ChequeNo {
            get {
                return ResourceManager.GetString("ChequeNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claimable Amount ($).
        /// </summary>
        internal static string ClaimableAmount {
            get {
                return ResourceManager.GetString("ClaimableAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission.
        /// </summary>
        internal static string Commission {
            get {
                return ResourceManager.GetString("Commission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission Desciption.
        /// </summary>
        internal static string CommissionDesciption {
            get {
                return ResourceManager.GetString("CommissionDesciption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you confirm to process payroll in selected employee(s)?
        ///Once comfirmed, the payroll will be auto-generated with default information..
        /// </summary>
        internal static string ConfirmationText {
            get {
                return ResourceManager.GetString("ConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF.
        /// </summary>
        internal static string CPF {
            get {
                return ResourceManager.GetString("CPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Wages.
        /// </summary>
        internal static string CPFAddWages {
            get {
                return ResourceManager.GetString("CPFAddWages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF Contribution.
        /// </summary>
        internal static string CPFCont {
            get {
                return ResourceManager.GetString("CPFCont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF Deductable.
        /// </summary>
        internal static string CPFDeductable {
            get {
                return ResourceManager.GetString("CPFDeductable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF Employee.
        /// </summary>
        internal static string CPFEmpe {
            get {
                return ResourceManager.GetString("CPFEmpe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee List.
        /// </summary>
        internal static string CPFEmpeList {
            get {
                return ResourceManager.GetString("CPFEmpeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAT - CPF Configuration.
        /// </summary>
        internal static string CPFFileConfig {
            get {
                return ResourceManager.GetString("CPFFileConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Local Path.
        /// </summary>
        internal static string CPFFileLocalPath {
            get {
                return ResourceManager.GetString("CPFFileLocalPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF Formula.
        /// </summary>
        internal static string CPFFormula {
            get {
                return ResourceManager.GetString("CPFFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAT - Submit CPF File.
        /// </summary>
        internal static string CPFGenerateFile {
            get {
                return ResourceManager.GetString("CPFGenerateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAT - CPF Employees List.
        /// </summary>
        internal static string CPFGenerateFileDetail {
            get {
                return ResourceManager.GetString("CPFGenerateFileDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordinary Wages.
        /// </summary>
        internal static string CPFOrdWages {
            get {
                return ResourceManager.GetString("CPFOrdWages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race.
        /// </summary>
        internal static string CPFRace {
            get {
                return ResourceManager.GetString("CPFRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residential Status.
        /// </summary>
        internal static string CPFResStatus {
            get {
                return ResourceManager.GetString("CPFResStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF File.
        /// </summary>
        internal static string CPF_File {
            get {
                return ResourceManager.GetString("CPF_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .DAT.
        /// </summary>
        internal static string DAT {
            get {
                return ResourceManager.GetString("DAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Applied.
        /// </summary>
        internal static string DateApplied {
            get {
                return ResourceManager.GetString("DateApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll Run Date.
        /// </summary>
        internal static string DateOfPayment {
            get {
                return ResourceManager.GetString("DateOfPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days Worked.
        /// </summary>
        internal static string Days_Worked {
            get {
                return ResourceManager.GetString("Days_Worked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deduct in Payroll ?.
        /// </summary>
        internal static string DeductInPayroll {
            get {
                return ResourceManager.GetString("DeductInPayroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deductions.
        /// </summary>
        internal static string Deductions {
            get {
                return ResourceManager.GetString("Deductions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deductions Amount.
        /// </summary>
        internal static string DeductionsAmount {
            get {
                return ResourceManager.GetString("DeductionsAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deduction (Donation).
        /// </summary>
        internal static string Deduction_Donation {
            get {
                return ResourceManager.GetString("Deduction_Donation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation.
        /// </summary>
        internal static string Designation {
            get {
                return ResourceManager.GetString("Designation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Director Fee.
        /// </summary>
        internal static string DirectorFee {
            get {
                return ResourceManager.GetString("DirectorFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donation.
        /// </summary>
        internal static string Donation {
            get {
                return ResourceManager.GetString("Donation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donation Description.
        /// </summary>
        internal static string DonationDesc {
            get {
                return ResourceManager.GetString("DonationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donation Formula.
        /// </summary>
        internal static string DonationFormula {
            get {
                return ResourceManager.GetString("DonationFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donation Name.
        /// </summary>
        internal static string DonationName {
            get {
                return ResourceManager.GetString("DonationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donation Type.
        /// </summary>
        internal static string DonationType {
            get {
                return ResourceManager.GetString("DonationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donation Type.
        /// </summary>
        internal static string Donation_Type {
            get {
                return ResourceManager.GetString("Donation_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .DTL.
        /// </summary>
        internal static string DTL {
            get {
                return ResourceManager.GetString("DTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECF.
        /// </summary>
        internal static string ECF {
            get {
                return ResourceManager.GetString("ECF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Date.
        /// </summary>
        internal static string EffectiveDate {
            get {
                return ResourceManager.GetString("EffectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        internal static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee&apos;s Contribution.
        /// </summary>
        internal static string EmployeeContribution {
            get {
                return ResourceManager.GetString("EmployeeContribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee&apos;s CPF Contribution.
        /// </summary>
        internal static string EmployeeCPFContribution {
            get {
                return ResourceManager.GetString("EmployeeCPFContribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Information.
        /// </summary>
        internal static string EmployeeInformation {
            get {
                return ResourceManager.GetString("EmployeeInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee&apos;s Name.
        /// </summary>
        internal static string EmployeeName {
            get {
                return ResourceManager.GetString("EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee No.
        /// </summary>
        internal static string EmployeeNo {
            get {
                return ResourceManager.GetString("EmployeeNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer&apos;s Contribution.
        /// </summary>
        internal static string EmployerContribution {
            get {
                return ResourceManager.GetString("EmployerContribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer&apos;s CPF Contribution.
        /// </summary>
        internal static string EmployerCPFContribution {
            get {
                return ResourceManager.GetString("EmployerCPFContribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer&apos;s Name.
        /// </summary>
        internal static string EmployerName {
            get {
                return ResourceManager.GetString("EmployerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses.
        /// </summary>
        internal static string Expenses {
            get {
                return ResourceManager.GetString("Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses Claimable Amount.
        /// </summary>
        internal static string ExpensesAmount {
            get {
                return ResourceManager.GetString("ExpensesAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses Date.
        /// </summary>
        internal static string ExpensesDate {
            get {
                return ResourceManager.GetString("ExpensesDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses Period.
        /// </summary>
        internal static string ExpensesPeriod {
            get {
                return ResourceManager.GetString("ExpensesPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses Record Period.
        /// </summary>
        internal static string ExpensesPeriodFrom {
            get {
                return ResourceManager.GetString("ExpensesPeriodFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string ExpensesPeriodTo {
            get {
                return ResourceManager.GetString("ExpensesPeriodTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses Record.
        /// </summary>
        internal static string ExpensesRecord {
            get {
                return ResourceManager.GetString("ExpensesRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses Type.
        /// </summary>
        internal static string ExpensesType {
            get {
                return ResourceManager.GetString("ExpensesType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export CPF File.
        /// </summary>
        internal static string ExportCPF {
            get {
                return ResourceManager.GetString("ExportCPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export E-Submission.
        /// </summary>
        internal static string ExportESubmission {
            get {
                return ResourceManager.GetString("ExportESubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export All to PDF..
        /// </summary>
        internal static string Export_All_PDF {
            get {
                return ResourceManager.GetString("Export_All_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Donation.
        /// </summary>
        internal static string ExtraDonation {
            get {
                return ResourceManager.GetString("ExtraDonation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Donations.
        /// </summary>
        internal static string ExtraDonations {
            get {
                return ResourceManager.GetString("ExtraDonations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee Amount.
        /// </summary>
        internal static string FeeAmount {
            get {
                return ResourceManager.GetString("FeeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated Date.
        /// </summary>
        internal static string FileGeneratedDate {
            get {
                return ResourceManager.GetString("FileGeneratedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        internal static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Type.
        /// </summary>
        internal static string FileType {
            get {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF.
        /// </summary>
        internal static string FileTypeCPF {
            get {
                return ResourceManager.GetString("FileTypeCPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IR8A.
        /// </summary>
        internal static string FileTypeIR8A {
            get {
                return ResourceManager.GetString("FileTypeIR8A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formula.
        /// </summary>
        internal static string Formula {
            get {
                return ResourceManager.GetString("Formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formula Description.
        /// </summary>
        internal static string Formula_Desc {
            get {
                return ResourceManager.GetString("Formula_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formula Name.
        /// </summary>
        internal static string Formula_Name {
            get {
                return ResourceManager.GetString("Formula_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string Full_Name {
            get {
                return ResourceManager.GetString("Full_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate CPF.
        /// </summary>
        internal static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated No.
        /// </summary>
        internal static string GeneratedNo {
            get {
                return ResourceManager.GetString("GeneratedNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross Salary.
        /// </summary>
        internal static string GrossSalary {
            get {
                return ResourceManager.GetString("GrossSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GroupName.
        /// </summary>
        internal static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourly Rate.
        /// </summary>
        internal static string HourlyRate {
            get {
                return ResourceManager.GetString("HourlyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours Worked.
        /// </summary>
        internal static string HoursWorked {
            get {
                return ResourceManager.GetString("HoursWorked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR.
        /// </summary>
        internal static string HR {
            get {
                return ResourceManager.GetString("HR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Payroll.
        /// </summary>
        internal static string Import_Payroll {
            get {
                return ResourceManager.GetString("Import_Payroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IR8A.
        /// </summary>
        internal static string IR8A {
            get {
                return ResourceManager.GetString("IR8A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus.
        /// </summary>
        internal static string IR8ABonus {
            get {
                return ResourceManager.GetString("IR8ABonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF/ Designated pension/ fund.
        /// </summary>
        internal static string IR8ACPFDsgnPF {
            get {
                return ResourceManager.GetString("IR8ACPFDsgnPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Director&apos;s fee.
        /// </summary>
        internal static string IR8ADirectorsFee {
            get {
                return ResourceManager.GetString("IR8ADirectorsFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donation.
        /// </summary>
        internal static string IR8ADonation {
            get {
                return ResourceManager.GetString("IR8ADonation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAT - IR8A Configuration.
        /// </summary>
        internal static string IR8AFileConfig {
            get {
                return ResourceManager.GetString("IR8AFileConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate IR8A File.
        /// </summary>
        internal static string IR8AGenerate {
            get {
                return ResourceManager.GetString("IR8AGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAT - Submit IR8A File.
        /// </summary>
        internal static string IR8AGenerateFile {
            get {
                return ResourceManager.GetString("IR8AGenerateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAT - IR8A Employees List.
        /// </summary>
        internal static string IR8AGenerateFileDetail {
            get {
                return ResourceManager.GetString("IR8AGenerateFileDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross Commission.
        /// </summary>
        internal static string IR8AGrossCommission {
            get {
                return ResourceManager.GetString("IR8AGrossCommission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IR8A Information.
        /// </summary>
        internal static string IR8AInfo {
            get {
                return ResourceManager.GetString("IR8AInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance.
        /// </summary>
        internal static string IR8AInsurance {
            get {
                return ResourceManager.GetString("IR8AInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        internal static string IR8AOthers {
            get {
                return ResourceManager.GetString("IR8AOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pension.
        /// </summary>
        internal static string IR8APension {
            get {
                return ResourceManager.GetString("IR8APension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        internal static string IR8ASalary {
            get {
                return ResourceManager.GetString("IR8ASalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit IR8A File.
        /// </summary>
        internal static string IR8ASubmit {
            get {
                return ResourceManager.GetString("IR8ASubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount.
        /// </summary>
        internal static string IR8ATotalAmount {
            get {
                return ResourceManager.GetString("IR8ATotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IR8A File.
        /// </summary>
        internal static string IR8A_File {
            get {
                return ResourceManager.GetString("IR8A_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Director Fee this month?.
        /// </summary>
        internal static string IssueDirectorFee {
            get {
                return ResourceManager.GetString("IssueDirectorFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave.
        /// </summary>
        internal static string Leave {
            get {
                return ResourceManager.GetString("Leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Amount Deductable.
        /// </summary>
        internal static string LeaveAmount {
            get {
                return ResourceManager.GetString("LeaveAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Period.
        /// </summary>
        internal static string LeavePeriod {
            get {
                return ResourceManager.GetString("LeavePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Record Period.
        /// </summary>
        internal static string LeavePeriodFrom {
            get {
                return ResourceManager.GetString("LeavePeriodFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string LeavePeriodTo {
            get {
                return ResourceManager.GetString("LeavePeriodTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Record.
        /// </summary>
        internal static string LeaveRecord {
            get {
                return ResourceManager.GetString("LeaveRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Type.
        /// </summary>
        internal static string LeaveType {
            get {
                return ResourceManager.GetString("LeaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of employees.
        /// </summary>
        internal static string ListOfEmployees {
            get {
                return ResourceManager.GetString("ListOfEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Donation Type.
        /// </summary>
        internal static string MasterDonationType {
            get {
                return ResourceManager.GetString("MasterDonationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Extra donations.
        /// </summary>
        internal static string MasterExtraDonations {
            get {
                return ResourceManager.GetString("MasterExtraDonations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MBMF.
        /// </summary>
        internal static string MBMF {
            get {
                return ResourceManager.GetString("MBMF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode of payment.
        /// </summary>
        internal static string ModeOfPayment {
            get {
                return ResourceManager.GetString("ModeOfPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode of Payment.
        /// </summary>
        internal static string Mode_of_Payment {
            get {
                return ResourceManager.GetString("Mode_of_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Salary.
        /// </summary>
        internal static string NetSalary {
            get {
                return ResourceManager.GetString("NetSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Of Days.
        /// </summary>
        internal static string NoOfDays {
            get {
                return ResourceManager.GetString("NoOfDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Of Hours.
        /// </summary>
        internal static string NoOfHours {
            get {
                return ResourceManager.GetString("NoOfHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Applicable for.
        /// </summary>
        internal static string NotApplicableFor {
            get {
                return ResourceManager.GetString("NotApplicableFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Scheduler.
        /// </summary>
        internal static string NotificationScheduler {
            get {
                return ResourceManager.GetString("NotificationScheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Hours worked.
        /// </summary>
        internal static string NumberOfHoursWorked {
            get {
                return ResourceManager.GetString("NumberOfHoursWorked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overtime Formula.
        /// </summary>
        internal static string OTFormula {
            get {
                return ResourceManager.GetString("OTFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Allowances / Deductions.
        /// </summary>
        internal static string OtherAllowancesDeductions {
            get {
                return ResourceManager.GetString("OtherAllowancesDeductions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OT Hours.
        /// </summary>
        internal static string OT_Hours {
            get {
                return ResourceManager.GetString("OT_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OT Rate.
        /// </summary>
        internal static string OT_Rate {
            get {
                return ResourceManager.GetString("OT_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overtime.
        /// </summary>
        internal static string Overtime {
            get {
                return ResourceManager.GetString("Overtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overtime details.
        /// </summary>
        internal static string OvertimeDetails {
            get {
                return ResourceManager.GetString("OvertimeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overtime hour worked.
        /// </summary>
        internal static string OvertimeHourWorked {
            get {
                return ResourceManager.GetString("OvertimeHourWorked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overtime Amount Payable.
        /// </summary>
        internal static string OvertimePay {
            get {
                return ResourceManager.GetString("OvertimePay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overtime Payment Rate.
        /// </summary>
        internal static string OvertimePaymentRate {
            get {
                return ResourceManager.GetString("OvertimePaymentRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overtime period.
        /// </summary>
        internal static string OvertimePeriod {
            get {
                return ResourceManager.GetString("OvertimePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll.
        /// </summary>
        internal static string Payroll {
            get {
                return ResourceManager.GetString("Payroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll Configuration.
        /// </summary>
        internal static string PayrollConfiguration {
            get {
                return ResourceManager.GetString("PayrollConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll Configuration.
        /// </summary>
        internal static string PayrollConfiguration1 {
            get {
                return ResourceManager.GetString("PayrollConfiguration1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll Report.
        /// </summary>
        internal static string PayrollReport {
            get {
                return ResourceManager.GetString("PayrollReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payslip.
        /// </summary>
        internal static string Payslip {
            get {
                return ResourceManager.GetString("Payslip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payslip Summary.
        /// </summary>
        internal static string PayslipSummary {
            get {
                return ResourceManager.GetString("PayslipSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Payslip.
        /// </summary>
        internal static string PreviewPayslip {
            get {
                return ResourceManager.GetString("PreviewPayslip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        internal static string Process {
            get {
                return ResourceManager.GetString("Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Date.
        /// </summary>
        internal static string ProcessDate {
            get {
                return ResourceManager.GetString("ProcessDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Month.
        /// </summary>
        internal static string ProcessMonth {
            get {
                return ResourceManager.GetString("ProcessMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Month / Year.
        /// </summary>
        internal static string ProcessMonthYear {
            get {
                return ResourceManager.GetString("ProcessMonthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Year.
        /// </summary>
        internal static string ProcessYear {
            get {
                return ResourceManager.GetString("ProcessYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race.
        /// </summary>
        internal static string Race {
            get {
                return ResourceManager.GetString("Race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recur every.
        /// </summary>
        internal static string Recur_Every {
            get {
                return ResourceManager.GetString("Recur_Every", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Date.
        /// </summary>
        internal static string RunDate {
            get {
                return ResourceManager.GetString("RunDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDL.
        /// </summary>
        internal static string SDL {
            get {
                return ResourceManager.GetString("SDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected CPF Formula.
        /// </summary>
        internal static string SelectedCPFFormula {
            get {
                return ResourceManager.GetString("SelectedCPFFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Donation Formula.
        /// </summary>
        internal static string SelectedDonationFormula {
            get {
                return ResourceManager.GetString("SelectedDonationFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected OT Formula.
        /// </summary>
        internal static string SelectedOTFormula {
            get {
                return ResourceManager.GetString("SelectedOTFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIDA.
        /// </summary>
        internal static string SIDA {
            get {
                return ResourceManager.GetString("SIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission History.
        /// </summary>
        internal static string SubmissionHistory {
            get {
                return ResourceManager.GetString("SubmissionHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit CPF File.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbols.
        /// </summary>
        internal static string Symbols {
            get {
                return ResourceManager.GetString("Symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        internal static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total additional payment.
        /// </summary>
        internal static string TotalAdditionalPayment {
            get {
                return ResourceManager.GetString("TotalAdditionalPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Allowance.
        /// </summary>
        internal static string TotalAllowance {
            get {
                return ResourceManager.GetString("TotalAllowance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount.
        /// </summary>
        internal static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Bonus.
        /// </summary>
        internal static string TotalBonus {
            get {
                return ResourceManager.GetString("TotalBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Deduction.
        /// </summary>
        internal static string TotalDeduction {
            get {
                return ResourceManager.GetString("TotalDeduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Director Fee.
        /// </summary>
        internal static string TotalDirectorFee {
            get {
                return ResourceManager.GetString("TotalDirectorFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days Worked.
        /// </summary>
        internal static string TotalWorkDays {
            get {
                return ResourceManager.GetString("TotalWorkDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donation.
        /// </summary>
        internal static string Total_Donation {
            get {
                return ResourceManager.GetString("Total_Donation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger.
        /// </summary>
        internal static string Trigger {
            get {
                return ResourceManager.GetString("Trigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger Set Up.
        /// </summary>
        internal static string Trigger_Set_Up {
            get {
                return ResourceManager.GetString("Trigger_Set_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .TXT.
        /// </summary>
        internal static string TXT {
            get {
                return ResourceManager.GetString("TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables.
        /// </summary>
        internal static string Variables {
            get {
                return ResourceManager.GetString("Variables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://app.sbsolutions.com.sg/PAT/.
        /// </summary>
        internal static string _PATGenerateUrl {
            get {
                return ResourceManager.GetString("_PATGenerateUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pftpsn01.asianconnect.com.
        /// </summary>
        internal static string _sFTPDomainName {
            get {
                return ResourceManager.GetString("_sFTPDomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PTR003_openssh.key.
        /// </summary>
        internal static string _sFTPKeyFileName {
            get {
                return ResourceManager.GetString("_sFTPKeyFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\BlueCube\PAT\KeyFiles.
        /// </summary>
        internal static string _sFTPKeyFilePath {
            get {
                return ResourceManager.GetString("_sFTPKeyFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22.
        /// </summary>
        internal static string _sFTPPort {
            get {
                return ResourceManager.GetString("_sFTPPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /download/receive/.
        /// </summary>
        internal static string _sFTPUploadFilePath {
            get {
                return ResourceManager.GetString("_sFTPUploadFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /download/IRASreceive/.
        /// </summary>
        internal static string _sFTPUploadFilePathIR8A {
            get {
                return ResourceManager.GetString("_sFTPUploadFilePathIR8A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ptr003.
        /// </summary>
        internal static string _sFTPUserName {
            get {
                return ResourceManager.GetString("_sFTPUserName", resourceCulture);
            }
        }
    }
}
