//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceLeave {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceLeave() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceLeave", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Approval work flow.
        /// </summary>
        internal static string AddApprovalWorkflow {
            get {
                return ResourceManager.GetString("AddApprovalWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Holiday &amp; Event.
        /// </summary>
        internal static string AddHoliday {
            get {
                return ResourceManager.GetString("AddHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Leave Adjustment.
        /// </summary>
        internal static string AddLeaveAdjustment {
            get {
                return ResourceManager.GetString("AddLeaveAdjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Leave Type.
        /// </summary>
        internal static string AddLeaveType {
            get {
                return ResourceManager.GetString("AddLeaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address_While_On_Leave {
            get {
                return ResourceManager.GetString("Address_While_On_Leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment.
        /// </summary>
        internal static string Adjustment {
            get {
                return ResourceManager.GetString("Adjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment Amount.
        /// </summary>
        internal static string AdjustmentAmount {
            get {
                return ResourceManager.GetString("AdjustmentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow for Resignation notice period.
        /// </summary>
        internal static string AllowedNoticePeriod {
            get {
                return ResourceManager.GetString("AllowedNoticePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed for Probation.
        /// </summary>
        internal static string Allowed_Probation {
            get {
                return ResourceManager.GetString("Allowed_Probation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicable.
        /// </summary>
        internal static string Applicable {
            get {
                return ResourceManager.GetString("Applicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicable for.
        /// </summary>
        internal static string ApplicableFor {
            get {
                return ResourceManager.GetString("ApplicableFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval.
        /// </summary>
        internal static string Approval {
            get {
                return ResourceManager.GetString("Approval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Approval Workflow.
        /// </summary>
        internal static string ApprovalWorkflow {
            get {
                return ResourceManager.GetString("ApprovalWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Approval Workflow Information.
        /// </summary>
        internal static string ApprovalWorkflowInfo {
            get {
                return ResourceManager.GetString("ApprovalWorkflowInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Workflow List.
        /// </summary>
        internal static string ApprovalWorkflowList {
            get {
                return ResourceManager.GetString("ApprovalWorkflowList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-Approval.
        /// </summary>
        internal static string Approval_Status_1st {
            get {
                return ResourceManager.GetString("Approval_Status_1st", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-Approval.
        /// </summary>
        internal static string Approval_Status_2st {
            get {
                return ResourceManager.GetString("Approval_Status_2st", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        internal static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Cancellation Applications.
        /// </summary>
        internal static string ApprovedCancellationApplications {
            get {
                return ResourceManager.GetString("ApprovedCancellationApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Leave.
        /// </summary>
        internal static string ApprovedLeave {
            get {
                return ResourceManager.GetString("ApprovedLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Leave List.
        /// </summary>
        internal static string ApprovedLeaveList {
            get {
                return ResourceManager.GetString("ApprovedLeaveList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approver.
        /// </summary>
        internal static string Approver {
            get {
                return ResourceManager.GetString("Approver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        internal static string Branch {
            get {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bring Forward.
        /// </summary>
        internal static string BringForward {
            get {
                return ResourceManager.GetString("BringForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bring Forward to next year.
        /// </summary>
        internal static string Bring_Forward {
            get {
                return ResourceManager.GetString("Bring_Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        internal static string Bring_Forward_Days {
            get {
                return ResourceManager.GetString("Bring_Forward_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many days to bring forward?.
        /// </summary>
        internal static string Bring_Forward_Percent {
            get {
                return ResourceManager.GetString("Bring_Forward_Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bring Forward Percent.
        /// </summary>
        internal static string Bring_Forward_Percent_ {
            get {
                return ResourceManager.GetString("Bring_Forward_Percent_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Approved.
        /// </summary>
        internal static string CancelApproved {
            get {
                return ResourceManager.GetString("CancelApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation.
        /// </summary>
        internal static string Cancellation {
            get {
                return ResourceManager.GetString("Cancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citizenship.
        /// </summary>
        internal static string Citizenship {
            get {
                return ResourceManager.GetString("Citizenship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        internal static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact No.
        /// </summary>
        internal static string Contact_While_Overseas {
            get {
                return ResourceManager.GetString("Contact_While_Overseas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuously.
        /// </summary>
        internal static string Continuously {
            get {
                return ResourceManager.GetString("Continuously", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customized.
        /// </summary>
        internal static string Customized {
            get {
                return ResourceManager.GetString("Customized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customized Leave Type.
        /// </summary>
        internal static string CustomizedLeaveType {
            get {
                return ResourceManager.GetString("CustomizedLeaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ficial Year - Custom Fiscal Year.
        /// </summary>
        internal static string Custom_Fiscal_Year {
            get {
                return ResourceManager.GetString("Custom_Fiscal_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Fiscal Year.
        /// </summary>
        internal static string Custom_Fiscal_Year_ {
            get {
                return ResourceManager.GetString("Custom_Fiscal_Year_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Applied From.
        /// </summary>
        internal static string Date_Applied {
            get {
                return ResourceManager.GetString("Date_Applied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        internal static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days Taken.
        /// </summary>
        internal static string Days_Taken {
            get {
                return ResourceManager.GetString("Days_Taken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deduct in Payroll.
        /// </summary>
        internal static string Deduct_In_Payroll {
            get {
                return ResourceManager.GetString("Deduct_In_Payroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Leave Amount.
        /// </summary>
        internal static string DefaultLeaveAmount {
            get {
                return ResourceManager.GetString("DefaultLeaveAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Leave Type.
        /// </summary>
        internal static string DefaultLeaveType {
            get {
                return ResourceManager.GetString("DefaultLeaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Fiscal Year (31 Dec).
        /// </summary>
        internal static string Default_Fiscal_Year {
            get {
                return ResourceManager.GetString("Default_Fiscal_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegate Approval To.
        /// </summary>
        internal static string DelegateApprovalTo {
            get {
                return ResourceManager.GetString("DelegateApprovalTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegation.
        /// </summary>
        internal static string Delegation {
            get {
                return ResourceManager.GetString("Delegation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation.
        /// </summary>
        internal static string Designation {
            get {
                return ResourceManager.GetString("Designation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document required? .
        /// </summary>
        internal static string DocumentRequired {
            get {
                return ResourceManager.GetString("DocumentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eligible for.
        /// </summary>
        internal static string EligibleFor {
            get {
                return ResourceManager.GetString("EligibleFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        internal static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Name.
        /// </summary>
        internal static string EmployeeName {
            get {
                return ResourceManager.GetString("EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee No.
        /// </summary>
        internal static string EmployeeNo {
            get {
                return ResourceManager.GetString("EmployeeNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string End_Date {
            get {
                return ResourceManager.GetString("End_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Approval.
        /// </summary>
        internal static string FinalApproval {
            get {
                return ResourceManager.GetString("FinalApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Approver.
        /// </summary>
        internal static string FinalApprover {
            get {
                return ResourceManager.GetString("FinalApprover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Approval.
        /// </summary>
        internal static string FirstApproval {
            get {
                return ResourceManager.GetString("FirstApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Approver.
        /// </summary>
        internal static string FirstApprover {
            get {
                return ResourceManager.GetString("FirstApprover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiscal Year.
        /// </summary>
        internal static string Fiscal_Year {
            get {
                return ResourceManager.GetString("Fiscal_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flexibly.
        /// </summary>
        internal static string Flexibly {
            get {
                return ResourceManager.GetString("Flexibly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format Of Taking Leave.
        /// </summary>
        internal static string FormatOfTakingLeave {
            get {
                return ResourceManager.GetString("FormatOfTakingLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Day.
        /// </summary>
        internal static string FullDay {
            get {
                return ResourceManager.GetString("FullDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half Day.
        /// </summary>
        internal static string HalfDay {
            get {
                return ResourceManager.GetString("HalfDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday &amp; Event.
        /// </summary>
        internal static string Holiday {
            get {
                return ResourceManager.GetString("Holiday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday &amp; Event End Date.
        /// </summary>
        internal static string HolidayEndDate {
            get {
                return ResourceManager.GetString("HolidayEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday &amp; Event Information.
        /// </summary>
        internal static string HolidayInfo {
            get {
                return ResourceManager.GetString("HolidayInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Day/Half Day.
        /// </summary>
        internal static string HolidayLength {
            get {
                return ResourceManager.GetString("HolidayLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday &amp; Event List.
        /// </summary>
        internal static string HolidayList {
            get {
                return ResourceManager.GetString("HolidayList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday &amp; Event Name.
        /// </summary>
        internal static string HolidayName {
            get {
                return ResourceManager.GetString("HolidayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday &amp; Event Start Date.
        /// </summary>
        internal static string HolidayStartDate {
            get {
                return ResourceManager.GetString("HolidayStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday &amp; Event Length.
        /// </summary>
        internal static string Holiday_Length {
            get {
                return ResourceManager.GetString("Holiday_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Leave.
        /// </summary>
        internal static string Import_Leave {
            get {
                return ResourceManager.GetString("Import_Leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave.
        /// </summary>
        internal static string Leave {
            get {
                return ResourceManager.GetString("Leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Adjustment.
        /// </summary>
        internal static string LeaveAdjustment {
            get {
                return ResourceManager.GetString("LeaveAdjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Adjustment Information.
        /// </summary>
        internal static string LeaveAdjustmentInfo {
            get {
                return ResourceManager.GetString("LeaveAdjustmentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Adjustment List.
        /// </summary>
        internal static string LeaveAdjustmentList {
            get {
                return ResourceManager.GetString("LeaveAdjustmentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Approval.
        /// </summary>
        internal static string LeaveApproval {
            get {
                return ResourceManager.GetString("LeaveApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Configuration.
        /// </summary>
        internal static string LeaveConfig {
            get {
                return ResourceManager.GetString("LeaveConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Date.
        /// </summary>
        internal static string LeaveDate {
            get {
                return ResourceManager.GetString("LeaveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Information.
        /// </summary>
        internal static string LeaveInfo {
            get {
                return ResourceManager.GetString("LeaveInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Balance.
        /// </summary>
        internal static string LeaveLeft {
            get {
                return ResourceManager.GetString("LeaveLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Management.
        /// </summary>
        internal static string LeaveManagement {
            get {
                return ResourceManager.GetString("LeaveManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Name.
        /// </summary>
        internal static string LeaveName {
            get {
                return ResourceManager.GetString("LeaveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Record.
        /// </summary>
        internal static string LeaveRecord {
            get {
                return ResourceManager.GetString("LeaveRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Report.
        /// </summary>
        internal static string LeaveReport {
            get {
                return ResourceManager.GetString("LeaveReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Type Default.
        /// </summary>
        internal static string LeaveTypeDefault {
            get {
                return ResourceManager.GetString("LeaveTypeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Type Default Child.
        /// </summary>
        internal static string LeaveTypeDefaultChild {
            get {
                return ResourceManager.GetString("LeaveTypeDefaultChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Type Default Information.
        /// </summary>
        internal static string LeaveTypeDefaultInfo {
            get {
                return ResourceManager.GetString("LeaveTypeDefaultInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Type Default Normal.
        /// </summary>
        internal static string LeaveTypeDefaultNormal {
            get {
                return ResourceManager.GetString("LeaveTypeDefaultNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Type List.
        /// </summary>
        internal static string LeaveTypeList {
            get {
                return ResourceManager.GetString("LeaveTypeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Description.
        /// </summary>
        internal static string Leave_Description {
            get {
                return ResourceManager.GetString("Leave_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Type.
        /// </summary>
        internal static string Leave_Type {
            get {
                return ResourceManager.GetString("Leave_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Type Information.
        /// </summary>
        internal static string Leave_Type_Info {
            get {
                return ResourceManager.GetString("Leave_Type_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of employees.
        /// </summary>
        internal static string ListOfEmployees {
            get {
                return ResourceManager.GetString("ListOfEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marital Status.
        /// </summary>
        internal static string Marital_Status {
            get {
                return ResourceManager.GetString("Marital_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maternity validity  period after 1st application date.
        /// </summary>
        internal static string MaternityValidityPeriod {
            get {
                return ResourceManager.GetString("MaternityValidityPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. Leave to next year.
        /// </summary>
        internal static string MaxLeavetoNextYear {
            get {
                return ResourceManager.GetString("MaxLeavetoNextYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration period for brought forward leave.
        /// </summary>
        internal static string Months_To_Expiry {
            get {
                return ResourceManager.GetString("Months_To_Expiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Leave.
        /// </summary>
        internal static string MyLeave {
            get {
                return ResourceManager.GetString("MyLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Leave.
        /// </summary>
        internal static string NewApplication {
            get {
                return ResourceManager.GetString("NewApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Request.
        /// </summary>
        internal static string NewRequest {
            get {
                return ResourceManager.GetString("NewRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. of Days.
        /// </summary>
        internal static string NoOfDays {
            get {
                return ResourceManager.GetString("NoOfDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not applicable for.
        /// </summary>
        internal static string NotApplicableFor {
            get {
                return ResourceManager.GetString("NotApplicableFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Leave entitled.
        /// </summary>
        internal static string NumberOfLeaveEntitled {
            get {
                return ResourceManager.GetString("NumberOfLeaveEntitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Cancellation Applications.
        /// </summary>
        internal static string PendingCancellationApplications {
            get {
                return ResourceManager.GetString("PendingCancellationApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Leave Applications.
        /// </summary>
        internal static string PendingLeaveApplications {
            get {
                return ResourceManager.GetString("PendingLeaveApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        internal static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AM.
        /// </summary>
        internal static string PeriodAM {
            get {
                return ResourceManager.GetString("PeriodAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM.
        /// </summary>
        internal static string PeriodPM {
            get {
                return ResourceManager.GetString("PeriodPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Contact No.
        /// </summary>
        internal static string PrimaryContactNo {
            get {
                return ResourceManager.GetString("PrimaryContactNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Holiday.
        /// </summary>
        internal static string PublicHoliday {
            get {
                return ResourceManager.GetString("PublicHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        internal static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected Leave List.
        /// </summary>
        internal static string RejectedLeaveList {
            get {
                return ResourceManager.GetString("RejectedLeaveList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related to.
        /// </summary>
        internal static string RelatedTo {
            get {
                return ResourceManager.GetString("RelatedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        internal static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request From.
        /// </summary>
        internal static string RequestFrom {
            get {
                return ResourceManager.GetString("RequestFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviewer.
        /// </summary>
        internal static string Reviewer {
            get {
                return ResourceManager.GetString("Reviewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Contact No.
        /// </summary>
        internal static string SecondaryContactNo {
            get {
                return ResourceManager.GetString("SecondaryContactNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string Start_Date {
            get {
                return ResourceManager.GetString("Start_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Calendar.
        /// </summary>
        internal static string TeamCalendar {
            get {
                return ResourceManager.GetString("TeamCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Document.
        /// </summary>
        internal static string Upload_Document {
            get {
                return ResourceManager.GetString("Upload_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If allow taking leave flexibly, specify the valid period.
        /// </summary>
        internal static string ValidPeriod {
            get {
                return ResourceManager.GetString("ValidPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weeks.
        /// </summary>
        internal static string Weeks {
            get {
                return ResourceManager.GetString("Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weeks Taken.
        /// </summary>
        internal static string WeeksTaken {
            get {
                return ResourceManager.GetString("WeeksTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While On Leave (Optional).
        /// </summary>
        internal static string WhileOverseas {
            get {
                return ResourceManager.GetString("WhileOverseas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Days.
        /// </summary>
        internal static string WorkingDays {
            get {
                return ResourceManager.GetString("WorkingDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year(s) of service.
        /// </summary>
        internal static string YearsServices {
            get {
                return ResourceManager.GetString("YearsServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year(s) of services more than.
        /// </summary>
        internal static string Years_Services {
            get {
                return ResourceManager.GetString("Years_Services", resourceCulture);
            }
        }
    }
}
