//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceCompany {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceCompany() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceCompany", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting.
        /// </summary>
        internal static string Accounting {
            get {
                return ResourceManager.GetString("Accounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        internal static string AccountNumber {
            get {
                return ResourceManager.GetString("AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Owner.
        /// </summary>
        internal static string AccountOwner {
            get {
                return ResourceManager.GetString("AccountOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Password.
        /// </summary>
        internal static string API_Password {
            get {
                return ResourceManager.GetString("API_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Signature.
        /// </summary>
        internal static string API_Signature {
            get {
                return ResourceManager.GetString("API_Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Username.
        /// </summary>
        internal static string API_Username {
            get {
                return ResourceManager.GetString("API_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Detail.
        /// </summary>
        internal static string BankDetail {
            get {
                return ResourceManager.GetString("BankDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name.
        /// </summary>
        internal static string BankName {
            get {
                return ResourceManager.GetString("BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Address.
        /// </summary>
        internal static string Billing {
            get {
                return ResourceManager.GetString("Billing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        internal static string Branch {
            get {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Detail.
        /// </summary>
        internal static string CompanyDetail {
            get {
                return ResourceManager.GetString("CompanyDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Information.
        /// </summary>
        internal static string CompanyInfo {
            get {
                return ResourceManager.GetString("CompanyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Lists.
        /// </summary>
        internal static string CompanyLists {
            get {
                return ResourceManager.GetString("CompanyLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Registry.
        /// </summary>
        internal static string CompanyRegistry {
            get {
                return ResourceManager.GetString("CompanyRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string CompanySource {
            get {
                return ResourceManager.GetString("CompanySource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Tagline.
        /// </summary>
        internal static string CompanyTagline {
            get {
                return ResourceManager.GetString("CompanyTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF Submission No.
        /// </summary>
        internal static string CPFSubNo {
            get {
                return ResourceManager.GetString("CPFSubNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of activation.
        /// </summary>
        internal static string DateOfactivation {
            get {
                return ResourceManager.GetString("DateOfactivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Expiration.
        /// </summary>
        internal static string DateOfExpiration {
            get {
                return ResourceManager.GetString("DateOfExpiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Registration.
        /// </summary>
        internal static string DateOfRegistration {
            get {
                return ResourceManager.GetString("DateOfRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display On Reports.
        /// </summary>
        internal static string DisplayOnReports {
            get {
                return ResourceManager.GetString("DisplayOnReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Date.
        /// </summary>
        internal static string EffectiveDate {
            get {
                return ResourceManager.GetString("EffectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment.
        /// </summary>
        internal static string Environment {
            get {
                return ResourceManager.GetString("Environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Information.
        /// </summary>
        internal static string GeneralInformation {
            get {
                return ResourceManager.GetString("GeneralInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUID.
        /// </summary>
        internal static string GUID {
            get {
                return ResourceManager.GetString("GUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logistics.
        /// </summary>
        internal static string Logistics {
            get {
                return ResourceManager.GetString("Logistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Name.
        /// </summary>
        internal static string ModuleName {
            get {
                return ResourceManager.GetString("ModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Registration.
        /// </summary>
        internal static string ModuleRegister {
            get {
                return ResourceManager.GetString("ModuleRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. of Employees.
        /// </summary>
        internal static string NoOfEmployee {
            get {
                return ResourceManager.GetString("NoOfEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAT Password.
        /// </summary>
        internal static string patPassword {
            get {
                return ResourceManager.GetString("patPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAT User ID.
        /// </summary>
        internal static string patUserID {
            get {
                return ResourceManager.GetString("patUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payer&apos;s ID No.
        /// </summary>
        internal static string PayerIDNo {
            get {
                return ResourceManager.GetString("PayerIDNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payer&apos;s ID Type.
        /// </summary>
        internal static string PayerIDType {
            get {
                return ResourceManager.GetString("PayerIDType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayPal.
        /// </summary>
        internal static string PayPal {
            get {
                return ResourceManager.GetString("PayPal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Lead Time.
        /// </summary>
        internal static string PurchaseLeadTime {
            get {
                return ResourceManager.GetString("PurchaseLeadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report footer.
        /// </summary>
        internal static string Reportfooter {
            get {
                return ResourceManager.GetString("Reportfooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Range Day.
        /// </summary>
        internal static string ScheduleRangeDay {
            get {
                return ResourceManager.GetString("ScheduleRangeDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Securtiy Day.
        /// </summary>
        internal static string SecurtiyDay {
            get {
                return ResourceManager.GetString("SecurtiyDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State/ Province.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax ID.
        /// </summary>
        internal static string TaxID {
            get {
                return ResourceManager.GetString("TaxID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total License.
        /// </summary>
        internal static string TotalLicense {
            get {
                return ResourceManager.GetString("TotalLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unassigned License.
        /// </summary>
        internal static string UnassignedLicense {
            get {
                return ResourceManager.GetString("UnassignedLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string UserProfileName {
            get {
                return ResourceManager.GetString("UserProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip/ Postal Code.
        /// </summary>
        internal static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
