//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceQuotation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceQuotation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceQuotation", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted By.
        /// </summary>
        internal static string AcceptedBy {
            get {
                return ResourceManager.GetString("AcceptedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Information.
        /// </summary>
        internal static string AccInfo {
            get {
                return ResourceManager.GetString("AccInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Information.
        /// </summary>
        internal static string AccountInformation {
            get {
                return ResourceManager.GetString("AccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        internal static string AccountName {
            get {
                return ResourceManager.GetString("AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Approval Workflow.
        /// </summary>
        internal static string AddApprovalWorkflow {
            get {
                return ResourceManager.GetString("AddApprovalWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Quotation.
        /// </summary>
        internal static string AddNewQuotation {
            get {
                return ResourceManager.GetString("AddNewQuotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Variable Order.
        /// </summary>
        internal static string AddNewVariableOrder {
            get {
                return ResourceManager.GetString("AddNewVariableOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Addr {
            get {
                return ResourceManager.GetString("Addr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount ($).
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual turn over.
        /// </summary>
        internal static string AnnualTurnOver {
            get {
                return ResourceManager.GetString("AnnualTurnOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicable For.
        /// </summary>
        internal static string ApplicableFor {
            get {
                return ResourceManager.GetString("ApplicableFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval.
        /// </summary>
        internal static string Approval {
            get {
                return ResourceManager.GetString("Approval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Status 1st.
        /// </summary>
        internal static string Approval_Status_1st {
            get {
                return ResourceManager.GetString("Approval_Status_1st", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Status 2st.
        /// </summary>
        internal static string Approval_Status_2st {
            get {
                return ResourceManager.GetString("Approval_Status_2st", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Quotation List.
        /// </summary>
        internal static string ApprovedQuotationList {
            get {
                return ResourceManager.GetString("ApprovedQuotationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned User.
        /// </summary>
        internal static string AssignedTo {
            get {
                return ResourceManager.GetString("AssignedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned User.
        /// </summary>
        internal static string AssignedUser {
            get {
                return ResourceManager.GetString("AssignedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attn To.
        /// </summary>
        internal static string AttnTo {
            get {
                return ResourceManager.GetString("AttnTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biz file.
        /// </summary>
        internal static string Bizfile {
            get {
                return ResourceManager.GetString("Bizfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation Total.
        /// </summary>
        internal static string CalculationTotal {
            get {
                return ResourceManager.GetString("CalculationTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        internal static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Stamp and Date.
        /// </summary>
        internal static string CompanyStampAndDate {
            get {
                return ResourceManager.GetString("CompanyStampAndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultant.
        /// </summary>
        internal static string Consultant {
            get {
                return ResourceManager.GetString("Consultant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to Invoice.
        /// </summary>
        internal static string ConvertToInvoice {
            get {
                return ResourceManager.GetString("ConvertToInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to Opportunity.
        /// </summary>
        internal static string ConvertToOpportunity {
            get {
                return ResourceManager.GetString("ConvertToOpportunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created On.
        /// </summary>
        internal static string CreatedOn {
            get {
                return ResourceManager.GetString("CreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Proposal.
        /// </summary>
        internal static string DateOfProposal {
            get {
                return ResourceManager.GetString("DateOfProposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date valid until.
        /// </summary>
        internal static string DateValidUntil {
            get {
                return ResourceManager.GetString("DateValidUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Next Starting Number.
        /// </summary>
        internal static string DefaultNextStartingNumber {
            get {
                return ResourceManager.GetString("DefaultNextStartingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegation.
        /// </summary>
        internal static string Delegation {
            get {
                return ResourceManager.GetString("Delegation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        internal static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Approver.
        /// </summary>
        internal static string FinalApprover {
            get {
                return ResourceManager.GetString("FinalApprover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Approver.
        /// </summary>
        internal static string FirstApprover {
            get {
                return ResourceManager.GetString("FirstApprover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to generate Quotation manually?.
        /// </summary>
        internal static string GenerateQuotationManual {
            get {
                return ResourceManager.GetString("GenerateQuotationManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Reference No.
        /// </summary>
        internal static string GenerateRefNo {
            get {
                return ResourceManager.GetString("GenerateRefNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GST.
        /// </summary>
        internal static string GST {
            get {
                return ResourceManager.GetString("GST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICV case?.
        /// </summary>
        internal static string ICVcase {
            get {
                return ResourceManager.GetString("ICVcase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICV submission.
        /// </summary>
        internal static string ICVsubmission {
            get {
                return ResourceManager.GetString("ICVsubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Include this page).
        /// </summary>
        internal static string IncludeThisPage {
            get {
                return ResourceManager.GetString("IncludeThisPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        internal static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Description.
        /// </summary>
        internal static string ItemDescription {
            get {
                return ResourceManager.GetString("ItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        internal static string ItemName {
            get {
                return ResourceManager.GetString("ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        internal static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Invoice.
        /// </summary>
        internal static string myInvoice {
            get {
                return ResourceManager.GetString("myInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Quotation.
        /// </summary>
        internal static string myQuotation {
            get {
                return ResourceManager.GetString("myQuotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name and Signature.
        /// </summary>
        internal static string NameAndSignature {
            get {
                return ResourceManager.GetString("NameAndSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Quotation.
        /// </summary>
        internal static string NewQuotation {
            get {
                return ResourceManager.GetString("NewQuotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. of Employee.
        /// </summary>
        internal static string NoOfEmployee {
            get {
                return ResourceManager.GetString("NoOfEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Page.
        /// </summary>
        internal static string NoOfPage {
            get {
                return ResourceManager.GetString("NoOfPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Applicable For.
        /// </summary>
        internal static string NotApplicableFor {
            get {
                return ResourceManager.GetString("NotApplicableFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunity.
        /// </summary>
        internal static string Opportunity {
            get {
                return ResourceManager.GetString("Opportunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Applications.
        /// </summary>
        internal static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Quotation Application.
        /// </summary>
        internal static string PendingQuotationApplication {
            get {
                return ResourceManager.GetString("PendingQuotationApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person-In-Charge.
        /// </summary>
        internal static string PersonInCharge {
            get {
                return ResourceManager.GetString("PersonInCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone No.
        /// </summary>
        internal static string PhoneNo {
            get {
                return ResourceManager.GetString("PhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        internal static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix.
        /// </summary>
        internal static string Prefix {
            get {
                return ResourceManager.GetString("Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepared By.
        /// </summary>
        internal static string PreparedBy {
            get {
                return ResourceManager.GetString("PreparedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Proposal.
        /// </summary>
        internal static string ProposalDate {
            get {
                return ResourceManager.GetString("ProposalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposal description.
        /// </summary>
        internal static string ProposalDescription {
            get {
                return ResourceManager.GetString("ProposalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposal For.
        /// </summary>
        internal static string ProposalFor {
            get {
                return ResourceManager.GetString("ProposalFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order No.
        /// </summary>
        internal static string PurchaseOrder {
            get {
                return ResourceManager.GetString("PurchaseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        internal static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation Information.
        /// </summary>
        internal static string QuoInfo {
            get {
                return ResourceManager.GetString("QuoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation.
        /// </summary>
        internal static string Quotation {
            get {
                return ResourceManager.GetString("Quotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation And Invoice.
        /// </summary>
        internal static string QuotationAndInvoice {
            get {
                return ResourceManager.GetString("QuotationAndInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation Approval.
        /// </summary>
        internal static string QuotationApproval {
            get {
                return ResourceManager.GetString("QuotationApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation Approval Workflow.
        /// </summary>
        internal static string QuotationApprovalWorkflow {
            get {
                return ResourceManager.GetString("QuotationApprovalWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation Configuration.
        /// </summary>
        internal static string QuotationConfiguration {
            get {
                return ResourceManager.GetString("QuotationConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation Details.
        /// </summary>
        internal static string QuotationDetails {
            get {
                return ResourceManager.GetString("QuotationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation Information.
        /// </summary>
        internal static string QuotationInfo {
            get {
                return ResourceManager.GetString("QuotationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation Item.
        /// </summary>
        internal static string QuotationItem {
            get {
                return ResourceManager.GetString("QuotationItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation Management.
        /// </summary>
        internal static string QuotationManagement {
            get {
                return ResourceManager.GetString("QuotationManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to generate Quotation manually?.
        /// </summary>
        internal static string QuotationManual {
            get {
                return ResourceManager.GetString("QuotationManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation No.
        /// </summary>
        internal static string QuotationNo {
            get {
                return ResourceManager.GetString("QuotationNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation Revision.
        /// </summary>
        internal static string QuotationRevision {
            get {
                return ResourceManager.GetString("QuotationRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation Stage.
        /// </summary>
        internal static string QuotationStage {
            get {
                return ResourceManager.GetString("QuotationStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation Status.
        /// </summary>
        internal static string QuotationStatus {
            get {
                return ResourceManager.GetString("QuotationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation Template.
        /// </summary>
        internal static string QuotationTemplate {
            get {
                return ResourceManager.GetString("QuotationTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation Template List.
        /// </summary>
        internal static string QuotationTemplateList {
            get {
                return ResourceManager.GetString("QuotationTemplateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference ID.
        /// </summary>
        internal static string ReferenceID {
            get {
                return ResourceManager.GetString("ReferenceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference No.
        /// </summary>
        internal static string ReferenceNo {
            get {
                return ResourceManager.GetString("ReferenceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected/ Approved Applications.
        /// </summary>
        internal static string RejectedApproved {
            get {
                return ResourceManager.GetString("RejectedApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected Quotation List.
        /// </summary>
        internal static string RejectedQuotationList {
            get {
                return ResourceManager.GetString("RejectedQuotationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        internal static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision No.
        /// </summary>
        internal static string RevisionNo {
            get {
                return ResourceManager.GetString("RevisionNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales person name.
        /// </summary>
        internal static string SalesPersonName {
            get {
                return ResourceManager.GetString("SalesPersonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        internal static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Total ($).
        /// </summary>
        internal static string SubTotal {
            get {
                return ResourceManager.GetString("SubTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp; Conditions.
        /// </summary>
        internal static string TandC {
            get {
                return ResourceManager.GetString("TandC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        internal static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template ID.
        /// </summary>
        internal static string TemplateID {
            get {
                return ResourceManager.GetString("TemplateID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Name.
        /// </summary>
        internal static string TemplateName {
            get {
                return ResourceManager.GetString("TemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term of Payment.
        /// </summary>
        internal static string TermOfPayment {
            get {
                return ResourceManager.GetString("TermOfPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp; Conditions.
        /// </summary>
        internal static string TermsAndConditions {
            get {
                return ResourceManager.GetString("TermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount.
        /// </summary>
        internal static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price ($).
        /// </summary>
        internal static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total project fee payable.
        /// </summary>
        internal static string TotalProjectFeePayable {
            get {
                return ResourceManager.GetString("TotalProjectFeePayable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price ($).
        /// </summary>
        internal static string UnitPrice {
            get {
                return ResourceManager.GetString("UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validity.
        /// </summary>
        internal static string Validity {
            get {
                return ResourceManager.GetString("Validity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validity Period.
        /// </summary>
        internal static string ValidityPeriod {
            get {
                return ResourceManager.GetString("ValidityPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable Order Info.
        /// </summary>
        internal static string VariableOrderInfo {
            get {
                return ResourceManager.GetString("VariableOrderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yours Sincerely,.
        /// </summary>
        internal static string YoursSincerely {
            get {
                return ResourceManager.GetString("YoursSincerely", resourceCulture);
            }
        }
    }
}
