//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceEmployee {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceEmployee() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceEmployee", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Right.
        /// </summary>
        internal static string AccessRight {
            get {
                return ResourceManager.GetString("AccessRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        internal static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Employee.
        /// </summary>
        internal static string AddEmp {
            get {
                return ResourceManager.GetString("AddEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 1.
        /// </summary>
        internal static string Address_1 {
            get {
                return ResourceManager.GetString("Address_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 2.
        /// </summary>
        internal static string Address_2 {
            get {
                return ResourceManager.GetString("Address_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowance.
        /// </summary>
        internal static string Allowance {
            get {
                return ResourceManager.GetString("Allowance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowance Type.
        /// </summary>
        internal static string AllowanceType {
            get {
                return ResourceManager.GetString("AllowanceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment.
        /// </summary>
        internal static string Attachment {
            get {
                return ResourceManager.GetString("Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment File.
        /// </summary>
        internal static string AttachmentFile {
            get {
                return ResourceManager.GetString("AttachmentFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment Type.
        /// </summary>
        internal static string AttachmentType {
            get {
                return ResourceManager.GetString("AttachmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        internal static string Authentication {
            get {
                return ResourceManager.GetString("Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Information.
        /// </summary>
        internal static string BankInfo {
            get {
                return ResourceManager.GetString("BankInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Account.
        /// </summary>
        internal static string Bank_Account {
            get {
                return ResourceManager.GetString("Bank_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name.
        /// </summary>
        internal static string Bank_Name {
            get {
                return ResourceManager.GetString("Bank_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Salary.
        /// </summary>
        internal static string Basic_Salary {
            get {
                return ResourceManager.GetString("Basic_Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus Factor (Month).
        /// </summary>
        internal static string Bonus_Factor {
            get {
                return ResourceManager.GetString("Bonus_Factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        internal static string Branch {
            get {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Type.
        /// </summary>
        internal static string ChildType {
            get {
                return ResourceManager.GetString("ChildType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string Company_Name {
            get {
                return ResourceManager.GetString("Company_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Position.
        /// </summary>
        internal static string Company_Position {
            get {
                return ResourceManager.GetString("Company_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Date.
        /// </summary>
        internal static string Confirm_Date {
            get {
                return ResourceManager.GetString("Confirm_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact No.
        /// </summary>
        internal static string Contact_No {
            get {
                return ResourceManager.GetString("Contact_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Staff.
        /// </summary>
        internal static string ContractStaff {
            get {
                return ResourceManager.GetString("ContractStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract End Date.
        /// </summary>
        internal static string Contract_End_Date {
            get {
                return ResourceManager.GetString("Contract_End_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Start Date.
        /// </summary>
        internal static string Contract_Start_Date {
            get {
                return ResourceManager.GetString("Contract_Start_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Start-End Date.
        /// </summary>
        internal static string Contract_Start_End_Date {
            get {
                return ResourceManager.GetString("Contract_Start_End_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF.
        /// </summary>
        internal static string CPF {
            get {
                return ResourceManager.GetString("CPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF A/C No..
        /// </summary>
        internal static string CPF_AC_No {
            get {
                return ResourceManager.GetString("CPF_AC_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF Extraction Type.
        /// </summary>
        internal static string CPF_Type {
            get {
                return ResourceManager.GetString("CPF_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Salary.
        /// </summary>
        internal static string Current_Salary {
            get {
                return ResourceManager.GetString("Current_Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Rate.
        /// </summary>
        internal static string Daily_Rate {
            get {
                return ResourceManager.GetString("Daily_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Expiry.
        /// </summary>
        internal static string DateOfExpire {
            get {
                return ResourceManager.GetString("DateOfExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Issue.
        /// </summary>
        internal static string DateOfIssue {
            get {
                return ResourceManager.GetString("DateOfIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days Worked/WK.
        /// </summary>
        internal static string Days_Worked_WK {
            get {
                return ResourceManager.GetString("Days_Worked_WK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation.
        /// </summary>
        internal static string Designation {
            get {
                return ResourceManager.GetString("Designation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth.
        /// </summary>
        internal static string DOB {
            get {
                return ResourceManager.GetString("DOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Date.
        /// </summary>
        internal static string Effective_Date {
            get {
                return ResourceManager.GetString("Effective_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency.
        /// </summary>
        internal static string Emergency {
            get {
                return ResourceManager.GetString("Emergency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        internal static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Information.
        /// </summary>
        internal static string EmployeeInfo {
            get {
                return ResourceManager.GetString("EmployeeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Report.
        /// </summary>
        internal static string EmployeeReport {
            get {
                return ResourceManager.GetString("EmployeeReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Name.
        /// </summary>
        internal static string Employee_Name {
            get {
                return ResourceManager.GetString("Employee_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee No..
        /// </summary>
        internal static string Employee_No {
            get {
                return ResourceManager.GetString("Employee_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee No..
        /// </summary>
        internal static string Employee_Profile_ID {
            get {
                return ResourceManager.GetString("Employee_Profile_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employment History.
        /// </summary>
        internal static string EmploymentHistory {
            get {
                return ResourceManager.GetString("EmploymentHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employment History Information.
        /// </summary>
        internal static string EmploymentHistoryInfo {
            get {
                return ResourceManager.GetString("EmploymentHistoryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employment History List.
        /// </summary>
        internal static string EmploymentHistoryList {
            get {
                return ResourceManager.GetString("EmploymentHistoryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employment Type.
        /// </summary>
        internal static string EmploymentType {
            get {
                return ResourceManager.GetString("EmploymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error message.
        /// </summary>
        internal static string ErrorMsg {
            get {
                return ResourceManager.GetString("ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses Adjustment.
        /// </summary>
        internal static string ExpensesAdjustment {
            get {
                return ResourceManager.GetString("ExpensesAdjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry Date.
        /// </summary>
        internal static string Expiry_Date {
            get {
                return ResourceManager.GetString("Expiry_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Member.
        /// </summary>
        internal static string Family {
            get {
                return ResourceManager.GetString("Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Member.
        /// </summary>
        internal static string FamilyMember {
            get {
                return ResourceManager.GetString("FamilyMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hired Date.
        /// </summary>
        internal static string Hired_Date {
            get {
                return ResourceManager.GetString("Hired_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hire / Effective Date.
        /// </summary>
        internal static string HireEffectiveDate {
            get {
                return ResourceManager.GetString("HireEffectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hrs Worked/YR.
        /// </summary>
        internal static string Hours_Worked_YR {
            get {
                return ResourceManager.GetString("Hours_Worked_YR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR Information.
        /// </summary>
        internal static string HrInformation {
            get {
                return ResourceManager.GetString("HrInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immigration No.
        /// </summary>
        internal static string Immigration_No {
            get {
                return ResourceManager.GetString("Immigration_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Employee.
        /// </summary>
        internal static string ImportEmployee {
            get {
                return ResourceManager.GetString("ImportEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Date.
        /// </summary>
        internal static string Last_Effective_Date {
            get {
                return ResourceManager.GetString("Last_Effective_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Salary.
        /// </summary>
        internal static string LatestSalary {
            get {
                return ResourceManager.GetString("LatestSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Adjustment.
        /// </summary>
        internal static string LeaveAdjustment {
            get {
                return ResourceManager.GetString("LeaveAdjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marital Status.
        /// </summary>
        internal static string Marital_Status {
            get {
                return ResourceManager.GetString("Marital_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name.
        /// </summary>
        internal static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile No..
        /// </summary>
        internal static string MobileNo {
            get {
                return ResourceManager.GetString("MobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Phone.
        /// </summary>
        internal static string Mobile_Phone {
            get {
                return ResourceManager.GetString("Mobile_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        internal static string Module {
            get {
                return ResourceManager.GetString("Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Description.
        /// </summary>
        internal static string ModuleDesc {
            get {
                return ResourceManager.GetString("ModuleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        internal static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice Period.
        /// </summary>
        internal static string NoticePeriod {
            get {
                return ResourceManager.GetString("NoticePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPL Daily.
        /// </summary>
        internal static string NPL_Daily {
            get {
                return ResourceManager.GetString("NPL_Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NRIC / FIN No..
        /// </summary>
        internal static string NRIC {
            get {
                return ResourceManager.GetString("NRIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office No..
        /// </summary>
        internal static string OfficeNo {
            get {
                return ResourceManager.GetString("OfficeNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donation Opt Out.
        /// </summary>
        internal static string OptOut {
            get {
                return ResourceManager.GetString("OptOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport No..
        /// </summary>
        internal static string Passport {
            get {
                return ResourceManager.GetString("Passport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Type.
        /// </summary>
        internal static string Payment_Type {
            get {
                return ResourceManager.GetString("Payment_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permit.
        /// </summary>
        internal static string Permit {
            get {
                return ResourceManager.GetString("Permit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permit expiry date.
        /// </summary>
        internal static string Permit_Expiry_Date {
            get {
                return ResourceManager.GetString("Permit_Expiry_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permit No.
        /// </summary>
        internal static string Permit_No {
            get {
                return ResourceManager.GetString("Permit_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        internal static string PersonalInfo {
            get {
                return ResourceManager.GetString("PersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip/ Postal Code.
        /// </summary>
        internal static string Postal_Code {
            get {
                return ResourceManager.GetString("Postal_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PR Start-End Date.
        /// </summary>
        internal static string PR_Date {
            get {
                return ResourceManager.GetString("PR_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PR End Date.
        /// </summary>
        internal static string PR_End_Date {
            get {
                return ResourceManager.GetString("PR_End_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PR No.
        /// </summary>
        internal static string PR_No {
            get {
                return ResourceManager.GetString("PR_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PR Start Date.
        /// </summary>
        internal static string PR_Start_Date {
            get {
                return ResourceManager.GetString("PR_Start_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race.
        /// </summary>
        internal static string Race {
            get {
                return ResourceManager.GetString("Race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Status.
        /// </summary>
        internal static string Record_Status {
            get {
                return ResourceManager.GetString("Record_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship.
        /// </summary>
        internal static string Relationship {
            get {
                return ResourceManager.GetString("Relationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Religion.
        /// </summary>
        internal static string Religion {
            get {
                return ResourceManager.GetString("Religion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        internal static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename File.
        /// </summary>
        internal static string RenameFile {
            get {
                return ResourceManager.GetString("RenameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residential Phone.
        /// </summary>
        internal static string Residential_Phone {
            get {
                return ResourceManager.GetString("Residential_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residential Status.
        /// </summary>
        internal static string Residential_Status {
            get {
                return ResourceManager.GetString("Residential_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Description.
        /// </summary>
        internal static string RoleDesc {
            get {
                return ResourceManager.GetString("RoleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        internal static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        internal static string Salary {
            get {
                return ResourceManager.GetString("Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary Information.
        /// </summary>
        internal static string SalaryInfo {
            get {
                return ResourceManager.GetString("SalaryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary List.
        /// </summary>
        internal static string SalaryList {
            get {
                return ResourceManager.GetString("SalaryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Change.
        /// </summary>
        internal static string SaveChange {
            get {
                return ResourceManager.GetString("SaveChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S/N.
        /// </summary>
        internal static string SN {
            get {
                return ResourceManager.GetString("SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor.
        /// </summary>
        internal static string Supervisor {
            get {
                return ResourceManager.GetString("Supervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminated Date.
        /// </summary>
        internal static string Terminated_Date {
            get {
                return ResourceManager.GetString("Terminated_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Salary.
        /// </summary>
        internal static string UpdateSalary {
            get {
                return ResourceManager.GetString("UpdateSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded By.
        /// </summary>
        internal static string UploadedBy {
            get {
                return ResourceManager.GetString("UploadedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded On.
        /// </summary>
        internal static string UploadedOn {
            get {
                return ResourceManager.GetString("UploadedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Account.
        /// </summary>
        internal static string UserAccount {
            get {
                return ResourceManager.GetString("UserAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Role.
        /// </summary>
        internal static string UserRole {
            get {
                return ResourceManager.GetString("UserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working.
        /// </summary>
        internal static string Working {
            get {
                return ResourceManager.GetString("Working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Day / Hour.
        /// </summary>
        internal static string WorkingDayHour {
            get {
                return ResourceManager.GetString("WorkingDayHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Pass Type.
        /// </summary>
        internal static string Work_Pass_Type {
            get {
                return ResourceManager.GetString("Work_Pass_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WP Class/No.
        /// </summary>
        internal static string WP_Class {
            get {
                return ResourceManager.GetString("WP_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WP Start-End Date.
        /// </summary>
        internal static string WP_Date {
            get {
                return ResourceManager.GetString("WP_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WP End Date.
        /// </summary>
        internal static string WP_End_Date {
            get {
                return ResourceManager.GetString("WP_End_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WP No.
        /// </summary>
        internal static string WP_No {
            get {
                return ResourceManager.GetString("WP_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WP Start Date.
        /// </summary>
        internal static string WP_Start_Date {
            get {
                return ResourceManager.GetString("WP_Start_Date", resourceCulture);
            }
        }
    }
}
