//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceExpenses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceExpenses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceExpenses", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accumulative.
        /// </summary>
        internal static string Accumulative {
            get {
                return ResourceManager.GetString("Accumulative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Approval Workflow.
        /// </summary>
        internal static string AddApprovalWorkflow {
            get {
                return ResourceManager.GetString("AddApprovalWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Currency Setup.
        /// </summary>
        internal static string AddCurrencySetup {
            get {
                return ResourceManager.GetString("AddCurrencySetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Expenses Type.
        /// </summary>
        internal static string AddNewExpensesType {
            get {
                return ResourceManager.GetString("AddNewExpensesType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow over Amount per Year.
        /// </summary>
        internal static string AllowedOverAmountPerYear {
            get {
                return ResourceManager.GetString("AllowedOverAmountPerYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed for Probation.
        /// </summary>
        internal static string AllowedProbation {
            get {
                return ResourceManager.GetString("AllowedProbation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claimable Amount.
        /// </summary>
        internal static string AmountClaiming {
            get {
                return ResourceManager.GetString("AmountClaiming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount / Percentage.
        /// </summary>
        internal static string AmountPercentage {
            get {
                return ResourceManager.GetString("AmountPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Per Month.
        /// </summary>
        internal static string AmountPerMonth {
            get {
                return ResourceManager.GetString("AmountPerMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Per UOM.
        /// </summary>
        internal static string AmountPerUOM {
            get {
                return ResourceManager.GetString("AmountPerUOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount per Year.
        /// </summary>
        internal static string AmountPerYear {
            get {
                return ResourceManager.GetString("AmountPerYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Spent.
        /// </summary>
        internal static string AmountSpent {
            get {
                return ResourceManager.GetString("AmountSpent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval.
        /// </summary>
        internal static string Approval {
            get {
                return ResourceManager.GetString("Approval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-Approval.
        /// </summary>
        internal static string ApprovalStatus1st {
            get {
                return ResourceManager.GetString("ApprovalStatus1st", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-Approval.
        /// </summary>
        internal static string ApprovalStatus2st {
            get {
                return ResourceManager.GetString("ApprovalStatus2st", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses Approval Workflow.
        /// </summary>
        internal static string ApprovalWorkflow {
            get {
                return ResourceManager.GetString("ApprovalWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses Approval Workflow Information.
        /// </summary>
        internal static string ApprovalWorkflowInfo {
            get {
                return ResourceManager.GetString("ApprovalWorkflowInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        internal static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Expenses List.
        /// </summary>
        internal static string ApprovedExpensesList {
            get {
                return ResourceManager.GetString("ApprovedExpensesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approver.
        /// </summary>
        internal static string Approver {
            get {
                return ResourceManager.GetString("Approver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Fixed Rate.
        /// </summary>
        internal static string ByFixedRate {
            get {
                return ResourceManager.GetString("ByFixedRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Online.
        /// </summary>
        internal static string ByOnline {
            get {
                return ResourceManager.GetString("ByOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Description.
        /// </summary>
        internal static string Category_Description {
            get {
                return ResourceManager.GetString("Category_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        internal static string Category_Name {
            get {
                return ResourceManager.GetString("Category_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Type.
        /// </summary>
        internal static string ClaimableType {
            get {
                return ResourceManager.GetString("ClaimableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare Method.
        /// </summary>
        internal static string CompareMethod {
            get {
                return ResourceManager.GetString("CompareMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount / Per Default Currency.
        /// </summary>
        internal static string ConversionAmount {
            get {
                return ResourceManager.GetString("ConversionAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion Currency.
        /// </summary>
        internal static string ConversionCurrency {
            get {
                return ResourceManager.GetString("ConversionCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Setup.
        /// </summary>
        internal static string CurrencySetup {
            get {
                return ResourceManager.GetString("CurrencySetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Setup Information.
        /// </summary>
        internal static string CurrencySetupInfo {
            get {
                return ResourceManager.GetString("CurrencySetupInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Applied.
        /// </summary>
        internal static string DateApplied {
            get {
                return ResourceManager.GetString("DateApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default (31 Dec).
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Currency.
        /// </summary>
        internal static string DefaultCurrency {
            get {
                return ResourceManager.GetString("DefaultCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation.
        /// </summary>
        internal static string Designation {
            get {
                return ResourceManager.GetString("Designation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        internal static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Name.
        /// </summary>
        internal static string EmployeeName {
            get {
                return ResourceManager.GetString("EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee No.
        /// </summary>
        internal static string EmployeeNo {
            get {
                return ResourceManager.GetString("EmployeeNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses.
        /// </summary>
        internal static string Expenses {
            get {
                return ResourceManager.GetString("Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses Approval.
        /// </summary>
        internal static string ExpensesApproval {
            get {
                return ResourceManager.GetString("ExpensesApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses Category.
        /// </summary>
        internal static string ExpensesCategory {
            get {
                return ResourceManager.GetString("ExpensesCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses Configuration.
        /// </summary>
        internal static string ExpensesConfig {
            get {
                return ResourceManager.GetString("ExpensesConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Expenses.
        /// </summary>
        internal static string ExpensesDate {
            get {
                return ResourceManager.GetString("ExpensesDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses Description.
        /// </summary>
        internal static string ExpensesDescription {
            get {
                return ResourceManager.GetString("ExpensesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses Information.
        /// </summary>
        internal static string ExpensesInfo {
            get {
                return ResourceManager.GetString("ExpensesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses Management.
        /// </summary>
        internal static string ExpensesManagement {
            get {
                return ResourceManager.GetString("ExpensesManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses Name.
        /// </summary>
        internal static string ExpensesName {
            get {
                return ResourceManager.GetString("ExpensesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses No..
        /// </summary>
        internal static string ExpensesNo {
            get {
                return ResourceManager.GetString("ExpensesNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Record.
        /// </summary>
        internal static string ExpensesRecord {
            get {
                return ResourceManager.GetString("ExpensesRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses Report.
        /// </summary>
        internal static string ExpensesReport {
            get {
                return ResourceManager.GetString("ExpensesReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses Title.
        /// </summary>
        internal static string ExpensesTitle {
            get {
                return ResourceManager.GetString("ExpensesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses Type.
        /// </summary>
        internal static string ExpensesType {
            get {
                return ResourceManager.GetString("ExpensesType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses Type Description.
        /// </summary>
        internal static string ExpensesTypeDesc {
            get {
                return ResourceManager.GetString("ExpensesTypeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Approval.
        /// </summary>
        internal static string FinalApproval {
            get {
                return ResourceManager.GetString("FinalApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Approver.
        /// </summary>
        internal static string FinalApprover {
            get {
                return ResourceManager.GetString("FinalApprover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Approval.
        /// </summary>
        internal static string FirstApproval {
            get {
                return ResourceManager.GetString("FirstApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Approver.
        /// </summary>
        internal static string FirstApprover {
            get {
                return ResourceManager.GetString("FirstApprover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiscal Year.
        /// </summary>
        internal static string FiscalYear {
            get {
                return ResourceManager.GetString("FiscalYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Expenses.
        /// </summary>
        internal static string Import_Expenses {
            get {
                return ResourceManager.GetString("Import_Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Details.
        /// </summary>
        internal static string ItemDetails {
            get {
                return ResourceManager.GetString("ItemDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. Amount per Claim.
        /// </summary>
        internal static string MaxAmountPerClaim {
            get {
                return ResourceManager.GetString("MaxAmountPerClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mileage.
        /// </summary>
        internal static string Mileage {
            get {
                return ResourceManager.GetString("Mileage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Expenses.
        /// </summary>
        internal static string NewApplication {
            get {
                return ResourceManager.GetString("NewApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pecentage.
        /// </summary>
        internal static string Pecentage {
            get {
                return ResourceManager.GetString("Pecentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Expenses Applications.
        /// </summary>
        internal static string PendingExpensesApplications {
            get {
                return ResourceManager.GetString("PendingExpensesApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage * Total Amount.
        /// </summary>
        internal static string PercentageTotalAmount {
            get {
                return ResourceManager.GetString("PercentageTotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per Month.
        /// </summary>
        internal static string PerMonth {
            get {
                return ResourceManager.GetString("PerMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per Year.
        /// </summary>
        internal static string PerYear {
            get {
                return ResourceManager.GetString("PerYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range Below.
        /// </summary>
        internal static string RangeAmount {
            get {
                return ResourceManager.GetString("RangeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reasons.
        /// </summary>
        internal static string Reasons {
            get {
                return ResourceManager.GetString("Reasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        internal static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected Expenses List.
        /// </summary>
        internal static string RejectedExpensesList {
            get {
                return ResourceManager.GetString("RejectedExpensesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        internal static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Form.
        /// </summary>
        internal static string RequestForm {
            get {
                return ResourceManager.GetString("RequestForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Maximum per Expenses Claims.
        /// </summary>
        internal static string SelectAmountPercentage {
            get {
                return ResourceManager.GetString("SelectAmountPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        internal static string Tax {
            get {
                return ResourceManager.GetString("Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Calendar.
        /// </summary>
        internal static string TeamCalendar {
            get {
                return ResourceManager.GetString("TeamCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount.
        /// </summary>
        internal static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Of Measurement.
        /// </summary>
        internal static string UnitOfMeasurement {
            get {
                return ResourceManager.GetString("UnitOfMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt Upload.
        /// </summary>
        internal static string UploadReceipt {
            get {
                return ResourceManager.GetString("UploadReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years of Services.
        /// </summary>
        internal static string YearService {
            get {
                return ResourceManager.GetString("YearService", resourceCulture);
            }
        }
    }
}
