//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceConfig {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceConfig() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceConfig", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Lookup.
        /// </summary>
        internal static string Add_New_Lookup {
            get {
                return ResourceManager.GetString("Add_New_Lookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Configuration.
        /// </summary>
        internal static string CompanyConfig {
            get {
                return ResourceManager.GetString("CompanyConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company lookup config.
        /// </summary>
        internal static string CompanyLookupConfig {
            get {
                return ResourceManager.GetString("CompanyLookupConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to proceed with the change?.
        /// </summary>
        internal static string ConfirmSavingChanges {
            get {
                return ResourceManager.GetString("ConfirmSavingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create By.
        /// </summary>
        internal static string Create_By {
            get {
                return ResourceManager.GetString("Create_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create On.
        /// </summary>
        internal static string Create_On {
            get {
                return ResourceManager.GetString("Create_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global lookup config.
        /// </summary>
        internal static string GlobalLookupConfig {
            get {
                return ResourceManager.GetString("GlobalLookupConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup by Data.
        /// </summary>
        internal static string LookupByData {
            get {
                return ResourceManager.GetString("LookupByData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup by Definition.
        /// </summary>
        internal static string LookupByDefinition {
            get {
                return ResourceManager.GetString("LookupByDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup by Definition.
        /// </summary>
        internal static string Lookup_by_Definition {
            get {
                return ResourceManager.GetString("Lookup_by_Definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Configuration.
        /// </summary>
        internal static string MasterConfig {
            get {
                return ResourceManager.GetString("MasterConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee No. Pattern.
        /// </summary>
        internal static string Pattern {
            get {
                return ResourceManager.GetString("Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update By.
        /// </summary>
        internal static string Update_By {
            get {
                return ResourceManager.GetString("Update_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update On.
        /// </summary>
        internal static string Update_On {
            get {
                return ResourceManager.GetString("Update_On", resourceCulture);
            }
        }
    }
}
