//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcePOS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcePOS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourcePOS", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Member.
        /// </summary>
        internal static string AddMember {
            get {
                return ResourceManager.GetString("AddMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMEX.
        /// </summary>
        internal static string AMEX {
            get {
                return ResourceManager.GetString("AMEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Due.
        /// </summary>
        internal static string AmountDue {
            get {
                return ResourceManager.GetString("AmountDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Birthday Month Discount.
        /// </summary>
        internal static string ApplyBirthday {
            get {
                return ResourceManager.GetString("ApplyBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Code.
        /// </summary>
        internal static string ApprovalCode {
            get {
                return ResourceManager.GetString("ApprovalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back Order.
        /// </summary>
        internal static string BackOrder {
            get {
                return ResourceManager.GetString("BackOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday Discount.
        /// </summary>
        internal static string BirthdayDiscount {
            get {
                return ResourceManager.GetString("BirthdayDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday Month.
        /// </summary>
        internal static string BirthdayMonth {
            get {
                return ResourceManager.GetString("BirthdayMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        internal static string Branch {
            get {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch &amp; Terminal.
        /// </summary>
        internal static string BranchTerminal {
            get {
                return ResourceManager.GetString("BranchTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Type.
        /// </summary>
        internal static string CardType {
            get {
                return ResourceManager.GetString("CardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        internal static string Cash {
            get {
                return ResourceManager.GetString("Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Advanced.
        /// </summary>
        internal static string CashAdvanced {
            get {
                return ResourceManager.GetString("CashAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashier.
        /// </summary>
        internal static string Cashier {
            get {
                return ResourceManager.GetString("Cashier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Payment.
        /// </summary>
        internal static string CashPayment {
            get {
                return ResourceManager.GetString("CashPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        internal static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes.
        /// </summary>
        internal static string Changes {
            get {
                return ResourceManager.GetString("Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed Shift.
        /// </summary>
        internal static string ClosedShift {
            get {
                return ResourceManager.GetString("ClosedShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Shift.
        /// </summary>
        internal static string CloseShift {
            get {
                return ResourceManager.GetString("CloseShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Terminal.
        /// </summary>
        internal static string CloseTerminal {
            get {
                return ResourceManager.GetString("CloseTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Time.
        /// </summary>
        internal static string CloseTime {
            get {
                return ResourceManager.GetString("CloseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combine Payment.
        /// </summary>
        internal static string CombinePayment {
            get {
                return ResourceManager.GetString("CombinePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact No.
        /// </summary>
        internal static string ContactNo {
            get {
                return ResourceManager.GetString("ContactNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card.
        /// </summary>
        internal static string CreditCard {
            get {
                return ResourceManager.GetString("CreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit/Debit.
        /// </summary>
        internal static string CreditDebit {
            get {
                return ResourceManager.GetString("CreditDebit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        internal static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        internal static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Report.
        /// </summary>
        internal static string DailyReport {
            get {
                return ResourceManager.GetString("DailyReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Format.
        /// </summary>
        internal static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Record.
        /// </summary>
        internal static string DeleteRecord {
            get {
                return ResourceManager.GetString("DeleteRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diner&apos;s Club.
        /// </summary>
        internal static string DinersClub {
            get {
                return ResourceManager.GetString("DinersClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        internal static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Type.
        /// </summary>
        internal static string DiscountType {
            get {
                return ResourceManager.GetString("DiscountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Tables.
        /// </summary>
        internal static string DisplayTables {
            get {
                return ResourceManager.GetString("DisplayTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth.
        /// </summary>
        internal static string DOB {
            get {
                return ResourceManager.GetString("DOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Date.
        /// </summary>
        internal static string EffectiveDate {
            get {
                return ResourceManager.GetString("EffectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Discount.
        /// </summary>
        internal static string GroupDiscount {
            get {
                return ResourceManager.GetString("GroupDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Name.
        /// </summary>
        internal static string HostName {
            get {
                return ResourceManager.GetString("HostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Service Charge?.
        /// </summary>
        internal static string IncludeServiceCharge {
            get {
                return ResourceManager.GetString("IncludeServiceCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Surcharge?.
        /// </summary>
        internal static string IncludeSurcharge {
            get {
                return ResourceManager.GetString("IncludeSurcharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice No.
        /// </summary>
        internal static string InvoiceNo {
            get {
                return ResourceManager.GetString("InvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Receipt number by branch.
        /// </summary>
        internal static string IsByBranch {
            get {
                return ResourceManager.GetString("IsByBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebPRNT Enabled?.
        /// </summary>
        internal static string IsWebPRNT {
            get {
                return ResourceManager.GetString("IsWebPRNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JCB.
        /// </summary>
        internal static string JCB {
            get {
                return ResourceManager.GetString("JCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        internal static string MacAddress {
            get {
                return ResourceManager.GetString("MacAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Card.
        /// </summary>
        internal static string MasterCard {
            get {
                return ResourceManager.GetString("MasterCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member.
        /// </summary>
        internal static string Member {
            get {
                return ResourceManager.GetString("Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Card.
        /// </summary>
        internal static string MemberCard {
            get {
                return ResourceManager.GetString("MemberCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Card No..
        /// </summary>
        internal static string MemberCardNo {
            get {
                return ResourceManager.GetString("MemberCardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Configuration.
        /// </summary>
        internal static string MemberConfiguration {
            get {
                return ResourceManager.GetString("MemberConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Discount.
        /// </summary>
        internal static string MemberDiscount {
            get {
                return ResourceManager.GetString("MemberDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Name.
        /// </summary>
        internal static string MemberName {
            get {
                return ResourceManager.GetString("MemberName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Status.
        /// </summary>
        internal static string MemberStatus {
            get {
                return ResourceManager.GetString("MemberStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Amount.
        /// </summary>
        internal static string NetAmount {
            get {
                return ResourceManager.GetString("NetAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nets.
        /// </summary>
        internal static string Nets {
            get {
                return ResourceManager.GetString("Nets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Branch &amp; Terminal.
        /// </summary>
        internal static string NewBranchTerminal {
            get {
                return ResourceManager.GetString("NewBranchTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Sale.
        /// </summary>
        internal static string NewSale {
            get {
                return ResourceManager.GetString("NewSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Terminal Information.
        /// </summary>
        internal static string NewTerminalInfo {
            get {
                return ResourceManager.GetString("NewTerminalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NRIC No..
        /// </summary>
        internal static string NRICNo {
            get {
                return ResourceManager.GetString("NRICNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt No. Length.
        /// </summary>
        internal static string NumLenght {
            get {
                return ResourceManager.GetString("NumLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Bill.
        /// </summary>
        internal static string OpenBill {
            get {
                return ResourceManager.GetString("OpenBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Shift.
        /// </summary>
        internal static string OpenShift {
            get {
                return ResourceManager.GetString("OpenShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Time.
        /// </summary>
        internal static string OpenTime {
            get {
                return ResourceManager.GetString("OpenTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid By.
        /// </summary>
        internal static string PaidBy {
            get {
                return ResourceManager.GetString("PaidBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper Size.
        /// </summary>
        internal static string PaperSize {
            get {
                return ResourceManager.GetString("PaperSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Type.
        /// </summary>
        internal static string PaymentType {
            get {
                return ResourceManager.GetString("PaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone No..
        /// </summary>
        internal static string PhoneNo {
            get {
                return ResourceManager.GetString("PhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS.
        /// </summary>
        internal static string POS {
            get {
                return ResourceManager.GetString("POS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS Configuration.
        /// </summary>
        internal static string POSConfig {
            get {
                return ResourceManager.GetString("POSConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix.
        /// </summary>
        internal static string Prefix {
            get {
                return ResourceManager.GetString("Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer IP Address.
        /// </summary>
        internal static string PrinterIPAddress {
            get {
                return ResourceManager.GetString("PrinterIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Code.
        /// </summary>
        internal static string ProductCode {
            get {
                return ResourceManager.GetString("ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Group.
        /// </summary>
        internal static string ProductGroup {
            get {
                return ResourceManager.GetString("ProductGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        internal static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase History.
        /// </summary>
        internal static string PurchaseHistory {
            get {
                return ResourceManager.GetString("PurchaseHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty-on-Hand.
        /// </summary>
        internal static string QoH {
            get {
                return ResourceManager.GetString("QoH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity-on-Hand Report.
        /// </summary>
        internal static string QoHReport {
            get {
                return ResourceManager.GetString("QoHReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        internal static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt.
        /// </summary>
        internal static string Receipt {
            get {
                return ResourceManager.GetString("Receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt By.
        /// </summary>
        internal static string ReceiptBy {
            get {
                return ResourceManager.GetString("ReceiptBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt Configuration.
        /// </summary>
        internal static string ReceiptConfig {
            get {
                return ResourceManager.GetString("ReceiptConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt Footer text (Typically your return policy and other information.).
        /// </summary>
        internal static string ReceiptFooter {
            get {
                return ResourceManager.GetString("ReceiptFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt Header text.
        /// </summary>
        internal static string ReceiptHeader {
            get {
                return ResourceManager.GetString("ReceiptHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt No.
        /// </summary>
        internal static string ReceiptNo {
            get {
                return ResourceManager.GetString("ReceiptNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Amount.
        /// </summary>
        internal static string ReceivedAmount {
            get {
                return ResourceManager.GetString("ReceivedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeem Credits.
        /// </summary>
        internal static string RedeemCredits {
            get {
                return ResourceManager.GetString("RedeemCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Member No..
        /// </summary>
        internal static string RefCount {
            get {
                return ResourceManager.GetString("RefCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Balance.
        /// </summary>
        internal static string RemainingBalance {
            get {
                return ResourceManager.GetString("RemainingBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        internal static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        internal static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume Sale.
        /// </summary>
        internal static string ResumeSale {
            get {
                return ResourceManager.GetString("ResumeSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Close.
        /// </summary>
        internal static string SaleClose {
            get {
                return ResourceManager.GetString("SaleClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Dashboard.
        /// </summary>
        internal static string SalesDashboard {
            get {
                return ResourceManager.GetString("SalesDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample.
        /// </summary>
        internal static string Sample {
            get {
                return ResourceManager.GetString("Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Product.
        /// </summary>
        internal static string SearchProduct {
            get {
                return ResourceManager.GetString("SearchProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Card.
        /// </summary>
        internal static string SelectCard {
            get {
                return ResourceManager.GetString("SelectCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Charge.
        /// </summary>
        internal static string ServiceCharge {
            get {
                return ResourceManager.GetString("ServiceCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settlement Process.
        /// </summary>
        internal static string SettlementProcess {
            get {
                return ResourceManager.GetString("SettlementProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        internal static string Shift {
            get {
                return ResourceManager.GetString("Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Balance Report.
        /// </summary>
        internal static string StockBalanceReport {
            get {
                return ResourceManager.GetString("StockBalanceReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suffix.
        /// </summary>
        internal static string Suffix {
            get {
                return ResourceManager.GetString("Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surcharge.
        /// </summary>
        internal static string Surcharge {
            get {
                return ResourceManager.GetString("Surcharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If include, please enter.
        /// </summary>
        internal static string SurchargePercen {
            get {
                return ResourceManager.GetString("SurchargePercen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspend Sale.
        /// </summary>
        internal static string SuspendSale {
            get {
                return ResourceManager.GetString("SuspendSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table No..
        /// </summary>
        internal static string TableNo {
            get {
                return ResourceManager.GetString("TableNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal.
        /// </summary>
        internal static string Terminal {
            get {
                return ResourceManager.GetString("Terminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal Information.
        /// </summary>
        internal static string TerminalInfo {
            get {
                return ResourceManager.GetString("TerminalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal Name.
        /// </summary>
        internal static string TerminalName {
            get {
                return ResourceManager.GetString("TerminalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Up Credit.
        /// </summary>
        internal static string TopUpCredit {
            get {
                return ResourceManager.GetString("TopUpCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount.
        /// </summary>
        internal static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Discount.
        /// </summary>
        internal static string TotalDiscount {
            get {
                return ResourceManager.GetString("TotalDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Qty.
        /// </summary>
        internal static string TotalQty {
            get {
                return ResourceManager.GetString("TotalQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Received.
        /// </summary>
        internal static string TotalReceived {
            get {
                return ResourceManager.GetString("TotalReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Sales.
        /// </summary>
        internal static string TotalSales {
            get {
                return ResourceManager.GetString("TotalSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Sold.
        /// </summary>
        internal static string TotalSold {
            get {
                return ResourceManager.GetString("TotalSold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        internal static string UnitPrice {
            get {
                return ResourceManager.GetString("UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Hold Bill &amp; Back Order.
        /// </summary>
        internal static string ViewHoldBill {
            get {
                return ResourceManager.GetString("ViewHoldBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa.
        /// </summary>
        internal static string Visa {
            get {
                return ResourceManager.GetString("Visa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Void.
        /// </summary>
        internal static string Void {
            get {
                return ResourceManager.GetString("Void", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Void &amp; Refund.
        /// </summary>
        internal static string VoidAndRefund {
            get {
                return ResourceManager.GetString("VoidAndRefund", resourceCulture);
            }
        }
    }
}
